# Enable mouse support
set -g mouse on

# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5

# Setup status bar
# set -g status-style bg=default,fg=white,bright
set -g status-left " "
set -g status-right "#[fg=default]#S "

# True color support
set -g default-terminal "${TERM}"
set-option -sg terminal-overrides ",*:RGB"

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

# Set vi-mode
set-window-option -g mode-keys vi

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Setup border lines
set -g pane-border-lines simple

# Renumber windows
set -g renumber-windows on

# Vim style pane selection
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# List of plugins
set -g @tpm_plugins '            \
  tmux-plugins/tpm               \
  rkxdhx/tselc                   \
  christoomey/vim-tmux-navigator \
'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

